output := "default.pdf"
outdir := "build"

init:
    mkdir -p {{ outdir }}

build: init
    typst src/index.typ {{ outdir }}/{{ output }}

watch: init
    typst --watch src/index.typ {{ outdir }}/{{ output }}