serve:
    jupyter nbconvert --to slides --post serve
slides:
    jupyter nbconvert --to slides --output-dir ./build/slides/
pdf:
    jupyter nbconvert --to pdf --output-dir ./build/pdf/
html:
    jupyter nbconvert --to html --output-dir ./build/html/
latex:
    jupyter nbconvert --to latex --output-dir ./build/latex/
python:
    jupyter nbconvert --to script --output ./build/python/index.py
all: slides pdf html latex python

server:
    JUPYTER_TOKEN=local jupyter server